# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
