# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
